
import Navbar from "@/components/navbar/Navbar";
import "./globals.css";


export const metadata = {
  title: "Royal Catering",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body
      >
        <Navbar/>
        {children}
      </body>
    </html>
  );
}
